{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mojang",
    "module": "logging",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-1.2.7.jar",
          "url": "logging-1.2.7.jar",
          "size": 15343,
          "sha512": "4637804df47b9191de9d219a12374c45175e790dc230040946db541022fb06ee5f6c1fd07cd6700465a6add5e66e96bf364e410da32bfacc4044507424a96e1e",
          "sha256": "3dc3190204bac5f4184d8405bfe1f724f73a6a15a0d3f36ec7f69e6872c1a76c",
          "sha1": "24cb95ffb0e3433fd6e844c04e68009e504ca1c0",
          "md5": "d01ea99740509a58222a426cc36f5456"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j2-impl",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.2.7.jar",
          "url": "logging-1.2.7.jar",
          "size": 15343,
          "sha512": "4637804df47b9191de9d219a12374c45175e790dc230040946db541022fb06ee5f6c1fd07cd6700465a6add5e66e96bf364e410da32bfacc4044507424a96e1e",
          "sha256": "3dc3190204bac5f4184d8405bfe1f724f73a6a15a0d3f36ec7f69e6872c1a76c",
          "sha1": "24cb95ffb0e3433fd6e844c04e68009e504ca1c0",
          "md5": "d01ea99740509a58222a426cc36f5456"
        }
      ]
    }
  ]
}
