{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "neoform-runtime",
    "version": "2.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "neoform-runtime-2.0.18.jar",
          "url": "neoform-runtime-2.0.18.jar",
          "size": 304076,
          "sha512": "5ebf0fdd4a1cdc532e78f466ea99128e1d2de9778b480ed47b7cbf4b8d75628adadc1383fb2e475183867645298d31117312bde931ddaa7930f3a09254dcca08",
          "sha256": "ae6efde7f1199f0a3bbcc4c84a99df58c5abae4aea8c5f812811bf98bdc514c7",
          "sha1": "60a0158bc9c02f868cec2da5d8c1e1b34cae18d5",
          "md5": "3418a86d91121f8470472ad603f5db57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.eclipse.jdt",
          "module": "ecj",
          "version": {
            "requires": "3.42.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "srgutils",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "net.neoforged.installertools",
          "module": "problems-api",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "neoform-runtime-2.0.18.jar",
          "url": "neoform-runtime-2.0.18.jar",
          "size": 304076,
          "sha512": "5ebf0fdd4a1cdc532e78f466ea99128e1d2de9778b480ed47b7cbf4b8d75628adadc1383fb2e475183867645298d31117312bde931ddaa7930f3a09254dcca08",
          "sha256": "ae6efde7f1199f0a3bbcc4c84a99df58c5abae4aea8c5f812811bf98bdc514c7",
          "sha1": "60a0158bc9c02f868cec2da5d8c1e1b34cae18d5",
          "md5": "3418a86d91121f8470472ad603f5db57"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoform-runtime-2.0.18-all.jar",
          "url": "neoform-runtime-2.0.18-all.jar",
          "size": 4479682,
          "sha512": "efe2da16dd2fd4dfb2a3b962f16dea131ed77e36a32a17a613f2c65f32024fd6653e89911b337a5dc7ae07aa4785404922d4688323d1198cffec22e4e9842af5",
          "sha256": "1fe29864dfbad1ec41d54b35d308f078302b2f8785eebfb8b90d9cdcd9433cb9",
          "sha1": "af5a11e64f209ac5909434ac2617b6af19a02a8d",
          "md5": "96d9c422f7029d97c1a14e70ed65b47b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoform-runtime-2.0.18-sources.jar",
          "url": "neoform-runtime-2.0.18-sources.jar",
          "size": 131781,
          "sha512": "8f7ceb6a0214742b474d316e0ba9137435c5a76b6dee4afefe7ccfbb3f6146565cd0f30425b746f5337a930cbb467f6fdb39bc5a53a84b368404b0b38f6461b5",
          "sha256": "c168b0540a650a590167e296b21845522686bb0232e8e39212b9b4af5411fe65",
          "sha1": "e10b3661febe92fe29810441cc249816b9d7c501",
          "md5": "a83dac92bf25ce523decd75a79e565af"
        }
      ]
    },
    {
      "name": "changelog",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "changelog"
      },
      "files": [
        {
          "name": "neoform-runtime-2.0.18-changelog.txt",
          "url": "neoform-runtime-2.0.18-changelog.txt",
          "size": 23037,
          "sha512": "bf5d3fe4790d07cb43e6b528487c97b815f659c9e264e5f8f764785599bdfbd77efd97f6ba05ae0e0b14203110354a5a15dbdefe9891f114978ff959780e33dc",
          "sha256": "02bc304df655c5afb6caa75dce651c131f3ac438cbc91502cfb2036f212a1a61",
          "sha1": "19af06125be0952acf3c5ea74cfa92e6336370e9",
          "md5": "606c8369b46f7ef34fa4149aa1a8e164"
        }
      ]
    },
    {
      "name": "externalTools",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.codechicken",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.0.36"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.neoforged",
          "module": "AutoRenamingTool",
          "version": {
            "requires": "2.0.17"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "AutoRenamingTool",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.neoforged.jst",
          "module": "jst-cli-bundle",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "mergetool",
          "version": {
            "requires": "1.1.7"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "fatjar"
            }
          }
        },
        {
          "group": "net.neoforged.installertools",
          "module": "installertools",
          "version": {
            "requires": "4.0.12"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "installertools",
              "type": "jar",
              "extension": "jar",
              "classifier": "fatjar"
            }
          }
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoform-runtime-external-tools",
          "version": "2.0.18"
        }
      ]
    }
  ]
}
