{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mojang",
    "module": "text2speech",
    "version": "1.17.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "text2speech-1.17.9.jar",
          "url": "text2speech-1.17.9.jar",
          "size": 12243,
          "sha512": "e7a9ca0449f1fcde00f242043e6f2890993aed4d98621e77a46858c7c9f4a1e5134cc77c33dd2d3b83b2e7164e99a616e3aaefbe860bb209be23e74f7b32a29f",
          "sha256": "c2a95b499e76fada7dd63e9b0ec797b678d411c2b0ee6f37f4dc674662bfb0af",
          "sha1": "3cad216e3a7f0c19b4b394388bc9ffc446f13b14",
          "md5": "f5b05e8db22e2e0668b786e11ac9d3ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "ca.weblite",
          "module": "java-objc-bridge",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "text2speech-1.17.9.jar",
          "url": "text2speech-1.17.9.jar",
          "size": 12243,
          "sha512": "e7a9ca0449f1fcde00f242043e6f2890993aed4d98621e77a46858c7c9f4a1e5134cc77c33dd2d3b83b2e7164e99a616e3aaefbe860bb209be23e74f7b32a29f",
          "sha256": "c2a95b499e76fada7dd63e9b0ec797b678d411c2b0ee6f37f4dc674662bfb0af",
          "sha1": "3cad216e3a7f0c19b4b394388bc9ffc446f13b14",
          "md5": "f5b05e8db22e2e0668b786e11ac9d3ce"
        }
      ]
    }
  ]
}
