plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = '1.0.0'
group = 'dev.maire.nourished'

base {
    archivesName = 'nourished'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = '21.1.228'

    parchment {
        mappingsVersion = '2024.11.17'
        minecraftVersion = '1.21.1'
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', 'nourished'
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'nourished'
        }
        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'nourished'
        }
        data {
            data()
            programArguments.addAll '--mod', 'nourished',
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        nourished {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    maven { url = 'https://maven.architectury.dev/' }
    maven { url = 'https://maven.blamejared.com' }
    maven { url = 'https://www.cursemaven.com' }
}

dependencies {
    implementation "me.shedaniel.cloth:cloth-config-neoforge:21.11.153"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
