org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft & NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,]
neo_version=21.1.229
neo_version_range=[21.1.228,)
loader_version_range=[4,)

# Mappings
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Mod Info
mod_id=nourished
mod_name=Nourished
mod_license=MIT
mod_version=0.2.7-beta
mod_group_id=dev.maire.nourished
mod_authors=Marie
mod_description=Nourished is a nutrition mod for NeoForge 1.21.1 that tracks six food groups, rewards a varied diet, and applies balance buffs and neglect penalties. Includes an on-screen HUD, diet screen, and configurable modules for servers and modpacks. Requires MarieLib 0.1.1-beta.4+

# Dependencies
cloth_config_version=15.0.140
kubejs_version=2101.7.2-build.295
patchouli_version=1.21.1-93-NEOFORGE
maries_framework_version=0.1.1-beta.4
maries_framework_version_range=[0.1.1-beta.4,)
maries_lib_version=0.1.1-beta.4
