pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'NutritionalBalance'

def localMarieLibDir = file('../MarieLib')
gradle.ext.localMarieLibPresent = new File(localMarieLibDir, 'build.gradle').exists()

if (gradle.ext.localMarieLibPresent) {
    includeBuild('../MarieLib') {
        dependencySubstitution {
            substitute module('dev.marie.MariesLib:marieslib') using project(':')
        }
    }
}

def localMariesCompatDir = file('../MariesCompat')
gradle.ext.localMariesCompatPresent = new File(localMariesCompatDir, 'build.gradle').exists()

if (gradle.ext.localMariesCompatPresent) {
    includeBuild('../MariesCompat')
}
