pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'NutritionalBalance'

def localMariesFrameworkDir = file('../MariesFramework')
gradle.ext.localMariesFrameworkPresent = new File(localMariesFrameworkDir, 'build.gradle').exists()

if (gradle.ext.localMariesFrameworkPresent) {
    includeBuild('../MariesFramework') {
        dependencySubstitution {
            substitute module('dev.marie.MariesFramework:mariesframework') using project(':')
        }
    }
}

def localMariesCompatDir = file('../MariesCompat')
gradle.ext.localMariesCompatPresent = new File(localMariesCompatDir, 'build.gradle').exists()

if (gradle.ext.localMariesCompatPresent) {
    includeBuild('../MariesCompat')
}
