{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.installertools",
    "module": "installertools",
    "version": "4.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "installertools-4.0.12.jar",
          "url": "installertools-4.0.12.jar",
          "size": 110522,
          "sha512": "c0a85415b5eb3a8528f2d29eb6e7c686e75a9ed47f882db07e6ea220dd8da595c00a371cfa34c2dbb4f2f1886e8011023b6468f1acba973b9f8c8eb7a88c8cd9",
          "sha256": "bdd3933b2c248df3ac2753d3027be328e68f62eb9bd63d03c038a8986b1bacc8",
          "sha1": "abddc7c3c62b3a0745c92000b50e402c4dc2d233",
          "md5": "c64204d7d5f2d519e4db32dfa8179fcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "AutoRenamingTool",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "net.neoforged",
          "module": "srgutils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.nothome",
          "module": "javaxdelta",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "net.neoforged.installertools",
          "module": "cli-utils",
          "version": {
            "requires": "4.0.12"
          }
        },
        {
          "group": "net.neoforged.installertools",
          "module": "binarypatcher",
          "version": {
            "requires": "4.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "installertools-4.0.12.jar",
          "url": "installertools-4.0.12.jar",
          "size": 110522,
          "sha512": "c0a85415b5eb3a8528f2d29eb6e7c686e75a9ed47f882db07e6ea220dd8da595c00a371cfa34c2dbb4f2f1886e8011023b6468f1acba973b9f8c8eb7a88c8cd9",
          "sha256": "bdd3933b2c248df3ac2753d3027be328e68f62eb9bd63d03c038a8986b1bacc8",
          "sha1": "abddc7c3c62b3a0745c92000b50e402c4dc2d233",
          "md5": "c64204d7d5f2d519e4db32dfa8179fcb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "installertools-4.0.12-javadoc.jar",
          "url": "installertools-4.0.12-javadoc.jar",
          "size": 122559,
          "sha512": "bcb8ce08e40ca1c3f55a8c1d33791b0d957c28438903ac94450e9440f8daf49a508c48ea4be76d488ba8b6a1f2f078b0f2b0d56f74c38e8348b30c9a00cd6223",
          "sha256": "9031a6ce2e98e0346d88d0a2a38d30c17a4c1882bf53a162c86c2c6c6eb210f1",
          "sha1": "649102fc708d58ac07d4045d52a90d5e90b0fc42",
          "md5": "b2db10140b7252dbc89becec37c279b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "installertools-4.0.12-sources.jar",
          "url": "installertools-4.0.12-sources.jar",
          "size": 46476,
          "sha512": "80d293f78ee5a57a7476c360d737894c8308167ebecd979e6ca6c84637060ced55f41fc002e134912980cb0ffc4a65f712f8761247f5dae43e64ac43061733e2",
          "sha256": "9442ae3537a6414c6317d87d49a3c867b0f8834fee46cc6125b08d52004408e8",
          "sha1": "dff7295758f784fa0019507f5a241840df6012de",
          "md5": "1281279586cbe6ab69a721d582241fe3"
        }
      ]
    },
    {
      "name": "proguard",
      "attributes": {
        "org.gradle.dependency.bundling": "shadowed"
      },
      "files": [
        {
          "name": "installertools-4.0.12-fatjar.jar",
          "url": "installertools-4.0.12-fatjar.jar",
          "size": 813509,
          "sha512": "3503ba41d13bb5f4fe746dbb04f4afd37e4967ebfbd33fbe5ca69e66c9e9bba7dcf6747a47d2e7e615b831d082f97133f78c6e293ffda1248a449fddc791657e",
          "sha256": "ba3e9d27d9f5145f829ac94124e3d97b80f027949d690b430305734526f143db",
          "sha1": "94b6e47c3f51f8ca40f8c54720369a952b821e95",
          "md5": "8e0b4681a0cb1cd75d86cecc6b27e523"
        }
      ]
    }
  ]
}
