modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="Nourished"
version="v0.1.2-alpha"
displayName="Nourished"
logoFile="nourished_icon.png"
authors="Marie"
description="A true adventurer knows that survival depends on more than just filling your belly. Nourished tracks your diet diversity and rewards those who eat well — built for Farmer's Delight and Pam's HarvestCraft."