{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.jst",
    "module": "jst-cli-bundle",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jst-cli-bundle-2.0.6.jar",
          "url": "jst-cli-bundle-2.0.6.jar",
          "size": 57944672,
          "sha512": "970c7551bea5ea58c56de9e1c6d47e95482d3cdfa36dfa7506c8b64fec499dec0b188091d043273e54f882880dfd3d53e5d196e1fc1dc66ede836d0502cdda7e",
          "sha256": "14e1f20d33d1e6dde9d3714f7e9d5f0631d90639db96eb1a56289e3e0dddd790",
          "sha1": "041bc2dcac9fe41493bee064a7e07b63a5d08348",
          "md5": "58f845978390cec50a4045a768bcf4d8"
        }
      ]
    }
  ]
}
