{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "accesstransformers",
    "version": "13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-parser",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "accesstransformers-13.0.1.jar",
          "url": "accesstransformers-13.0.1.jar",
          "size": 18860,
          "sha512": "a6522ecefa2f5797f065d67a7e7f61274aab320a3ff8c9ddd172162dad4a4fa5cc3b07ad6180f8892c0d0cb0c3e0631fd8c099bd6d56f1cd94c0ca159a293803",
          "sha256": "d7354d343b276466d68856d93a78e90838eb2e729fb1a10d9425dbcb186f5a22",
          "sha1": "5c6200bc80dc1d38b984a106a04d488dddcd642c",
          "md5": "11b76d2b511dd68fd28cbc006e8fb214"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-parser",
          "version": {
            "requires": "13.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "accesstransformers-13.0.1.jar",
          "url": "accesstransformers-13.0.1.jar",
          "size": 18860,
          "sha512": "a6522ecefa2f5797f065d67a7e7f61274aab320a3ff8c9ddd172162dad4a4fa5cc3b07ad6180f8892c0d0cb0c3e0631fd8c099bd6d56f1cd94c0ca159a293803",
          "sha256": "d7354d343b276466d68856d93a78e90838eb2e729fb1a10d9425dbcb186f5a22",
          "sha1": "5c6200bc80dc1d38b984a106a04d488dddcd642c",
          "md5": "11b76d2b511dd68fd28cbc006e8fb214"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accesstransformers-13.0.1-sources.jar",
          "url": "accesstransformers-13.0.1-sources.jar",
          "size": 8725,
          "sha512": "802ebeb6950484adff7ea26be9838a0134b085401188839bb338ccd0e22463d9b1bda672b44014779c8c6e6004d8c1a7e833ca967cff2fafb04319d8c535e117",
          "sha256": "4befb51a90ef993ddfaa15089f459ebe94b0afd14af1c726b9c3af1580fb04a5",
          "sha1": "6c9662fac6933573e34892a7857cbbc1f33a4c97",
          "md5": "a8cabb9139f52427b7fbf760354bf179"
        }
      ]
    }
  ]
}
