[general]
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	decayRate = 0.1
	# Default: 1200
	# Range: > 1
	decayIntervalTicks = 1200
	enableEffects = true
	enableHUD = true
	showFoodTooltips = true

[thresholds]
	# Default: 0.25
	# Range: 0.0 ~ 1.0
	criticalThreshold = 0.25
	# Default: 0.4
	# Range: 0.0 ~ 1.0
	lowThreshold = 0.4
	# Default: 0.9
	# Range: 0.0 ~ 1.0
	excessThreshold = 0.9

[effects]
	# Default: 0.75
	# Range: 0.0 ~ 1.0
	bonusEffectThreshold = 0.75
	# Default: 0.25
	# Range: 0.0 ~ 1.0
	penaltyEffectThreshold = 0.25

	[nutrients.fruits]
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		fruits_decayRate = -1.0
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		fruits_criticalThreshold = -1.0

	[nutrients.vegetables]
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		vegetables_decayRate = -1.0
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		vegetables_criticalThreshold = -1.0

	[nutrients.proteins]
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		proteins_decayRate = -1.0
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		proteins_criticalThreshold = -1.0

	[nutrients.grains]
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		grains_decayRate = -1.0
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		grains_criticalThreshold = -1.0

	[nutrients.sugars]
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		sugars_decayRate = -1.0
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		sugars_criticalThreshold = -1.0

	[nutrients.dairy]
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		dairy_decayRate = -1.0
		# Default: -1.0
		# Range: -1.0 ~ 1.0
		dairy_criticalThreshold = -1.0
