[gui]
	#Allowed Values: BOTTOM_LEFT, TOP_LEFT, TOP_RIGHT, BOTTOM_RIGHT
	hudAnchor = "BOTTOM_LEFT"
	# Default: 0
	# Range: -2000 ~ 2000
	hudOffsetX = -6
	# Default: 0
	# Range: -2000 ~ 2000
	hudOffsetY = -387
	# Default: 60
	# Range: 40 ~ 120
	hudBarWidth = 60
	# Default: 1.0
	# Range: 0.5 ~ 1.5
	hudScale = 0.759
	# Default: 52
	# Range: 30 ~ 100
	hudReservedBottom = 52
	hudDraggable = true
	dietBarDragEnabled = true
	hideZeroNutrients = true
	dietBarOrder = []
